export const defaultQueries = [
  "Java 急招",
  "急招 Java",
  "Java 今日",
  "Java 最新",
  "Java 新岗位",
  "Java",
  "Java开发",
  "Java后端",
  "Java工程师",
  "后端开发",
  "服务端开发",
  "SpringBoot",
  "微服务 Java",
  "支付 Java",
  "清结算 Java",
  "供应链 Java",
  "ERP Java",
  "订单 Java",
  "金融 Java",
  "电商 Java",
  "SaaS Java",
  "云计算 Java",
  "AI Java",
  "工业互联网 Java",
  "物联网 Java",
  "Java RocketMQ",
  "Java SpringCloud",
  "Java Redis",
  "Java 校招",
  "Java 26届",
  "Java 应届",
  "Java 初级",
  "初级 Java",
  "Java 1-3年",
  "Java 经验不限",
  "Java 软件开发",
  "Java 研发",
];

export const defaultCities = [
  { label: "全国", key: "nationwide", code: "100010000", enabled: true },
  { label: "上海", key: "Shanghai", code: "101020100", enabled: true },
  { label: "北京", key: "Beijing", code: "101010100", enabled: true },
  { label: "深圳", key: "Shenzhen", code: "101280600", enabled: true },
  { label: "广州", key: "Guangzhou", code: "101280100", enabled: true },
  { label: "南京", key: "Nanjing", code: "101190100", enabled: true },
  { label: "苏州", key: "Suzhou", code: "101190400", enabled: true },
  { label: "成都", key: "Chengdu", code: "101270100", enabled: true },
  { label: "武汉", key: "Wuhan", code: "101200100", enabled: true },
  { label: "西安", key: "Xi'an", code: "101110100", enabled: true },
  { label: "无锡", key: "Wuxi", code: "101190200", enabled: true },
  { label: "宁波", key: "Ningbo", code: "101210400", enabled: true },
  { label: "合肥", key: "Hefei", code: "101220100", enabled: true },
  { label: "长沙", key: "Changsha", code: "101250100", enabled: true },
  { label: "厦门", key: "Xiamen", code: "101230200", enabled: true },
  { label: "福州", key: "Fuzhou", code: "101230100", enabled: true },
  { label: "青岛", key: "Qingdao", code: "101120200", enabled: true },
  { label: "济南", key: "Jinan", code: "101120100", enabled: true },
  { label: "天津", key: "Tianjin", code: "101030100", enabled: true },
  { label: "重庆", key: "Chongqing", code: "101040100", enabled: true },
  { label: "郑州", key: "Zhengzhou", code: "101180100", enabled: true },
  { label: "东莞", key: "Dongguan", code: "101281600", enabled: true },
  { label: "佛山", key: "Foshan", code: "101280800", enabled: true },
  { label: "杭州", key: "Hangzhou", code: "101210100", enabled: false },
];

export const defaultConfig = {
  target: 150,
  mode: "review",
  browserChannel: "chrome",
  profileDir: "data/browser-profile",
  headless: false,
  delayMs: 900,
  maxPagesPerQuery: 2,
  qualityMode: "better",
  minSalaryK: 12,
  allowedExperience: ["经验不限", "应届", "1年以内", "1-3年", "3-5年"],
  queries: defaultQueries,
  cities: defaultCities,
  hardExclusions: [
    "实习",
    "实习生",
    "实习转正",
    "intern",
    "管培",
    "储备干部",
    "博士",
    "架构师",
    "专家",
    "技术总监",
    "技术主管",
    "技术组长",
    "团队管理",
    "负责人",
    "合伙人",
    "讲师",
    "导师",
    "非开发岗",
    "交付导师",
    "OD岗位",
    "驻日本",
    "出差",
    "短期",
    "项目制",
  ],
  outsourcingSignals: [
    "外包",
    "驻场",
    "外派",
    "派遣",
    "客户现场",
    "项目现场",
    "人力外包",
    "人力资源",
    "人才科技",
    "人才服务",
    "招聘服务",
    "外企德科",
    "法本",
    "中软国际",
    "软通动力",
    "博彦科技",
    "新致软件",
    "汉克时代",
    "纬创软件",
    "佰钧成",
    "易宝软件",
    "人瑞",
    "东软",
    "亿达信息",
    "京北方",
    "万宝盛华",
    "德科",
    "德科信息",
    "CLPS",
    "华钦",
    "独创时代",
  ],
  preferredTech: [
    "Java",
    "Spring",
    "SpringBoot",
    "Spring Cloud",
    "MyBatis",
    "MySQL",
    "Redis",
    "RocketMQ",
    "Kafka",
    "微服务",
    "分布式",
    "Docker",
    "Kubernetes",
    "JVM",
    "Dubbo",
    "Nacos",
  ],
  preferredDomains: [
    "支付",
    "清结算",
    "结算",
    "对账",
    "资金",
    "银行",
    "金融",
    "交易",
    "订单",
    "ERP",
    "供应链",
    "采购",
    "仓储",
    "履约",
    "WMS",
    "物流",
    "SaaS",
    "工业",
    "物联网",
    "IoT",
    "智能硬件",
    "机器人",
    "新能源",
    "云平台",
    "中间件",
  ],
};
